fixing the next issue in the installation
Problem invoking WLST - Traceback (innermost last):
  File "/var/lib/openshift/54e5b94ee659c5dc3700003e/weblogic/container-scripts/create-wls-domain.py", line 105, in ?
  File "/tmp/WLSTOfflineIni5924694158817517391.py", line 73, in writeDomain
60300: Domain name is not specified.
60300: Specify the domain name.
	at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:56)
	at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2279)
	at com.oracle.cie.domain.script.jython.WLScriptContext.writeDomain(WLScriptContext.java:1392)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException:
com.oracle.cie.domain.script.ScriptException: 60300: Domain name missing.
60300: Domain name is not specified.
60300: Specify the domain name.